<?php namespace KetkzApi\Enums;

class KzDeliveryEnum
{
    const AKSAI           = 1; //'AKSAI'
    const AKTAU           = 2; //'AKTAU'
    const AKTOBE          = 3; //'AKTOBE'
    const ALMATA          = 4; //'ALMATA'
    const ASTANA_KURER    = 5; //'ASTANA-KURER'
    const ATYRAU          = 6; //'ATYRAU'
    const Beineu          = 8; //'Beineu'
    const EKIBASTUZ       = 9; //'EKIBASTUZ'
    const KARAGANDA       = 10; //'KARAGANDA'
    const KOKSHETAU       = 11; //'KOKSHETAU'
    const KOSTANAI        = 12; //'KOSTANAI'
    const KYLSARY         = 13; //'KYLSARY'
    const KYZYLORDA       = 14; //'KYZYLORDA'
    const PAVLODAR        = 15; //'PAVLODAR'
    const PETROPAVLOVSK   = 16; //'PETROPAVLOVSK'
    const RUDNYI          = 18; //'RUDNYI'
    const Saryagash       = 19; //'Saryagash'
    const SATPAEV         = 20; //'SATPAEV'
    const SEMEI           = 21; //'SEMEI'
    const SHIMKENT        = 22; //'SHIMKENT'
    const TALDYKORGAN     = 23; //'TALDYKORGAN'
    const TARAZ           = 24; //'TARAZ'
    const TEMIRTAU        = 25; //'TEMIRTAU'
    const TURKESTAN       = 26; //'TURKESTAN'
    const URALSK          = 27; //'URALSK'
    const UST_KAMENOGORSK = 28; //'UST-KAMENOGORSK'
    const ZHANAOZEN       = 29; //'ZHANAOZEN'
    const Zhetysai        = 30; //'Zhetysai'
    const ZHEZKAZGAN      = 31; //'ZHEZKAZGAN'
    const KAPSHAGAI       = 56; //'KAPSHAGAI'
    const Hromtau         = 86; //'Hromtau'
    const Kandagash       = 87; //'Kandagash'
    const Kaskelen        = 88; //'Kaskelen'
    const Uzynagash       = 89; //'Uzynagash'
    const Talgar          = 90; //'Talgar'
    const Balkhash        = 91; //'Balkhash'
    const Kentau          = 93; //'Kentau'
    const Shieli          = 94; //'Shieli'
    const Zharkent        = 95; //'Zharkent'
    const Zhanakorgan     = 96; //'Zhanakorgan'
    const Merke           = 97; //'Merke'

    const Post      = 32; //'Почта'
    const Shamalgan = 142; //'Shamalgan'
    const Esik      = 143; //'Esik'
    const Toretam   = 144; //'Toretam'

    const Shu  = 146; //'Shu'
    const Arys = 147; //'Arys'

//---- Киргизия
    const Bishkek_kurer       = 34; //'Бишкек курьер'
    const Karakol_kurer       = 35; //'Каракол курьер'
    const Osh_kurer           = 36; //'Ош курьер'
    const Narin_kurer         = 37; //'Нарын курьер'
    const KizilKiya_Kurer     = 38; //'Кызыл-Кия курьер'
    const Batken_kurer        = 39; //'Баткен курьер'
    const Talas_kurer         = 40; //'Талас курьер'
    const Karabalta_kurer     = 41; //'Карабалта курьер'
    const Tokmok_kurer        = 42; //'Токмок курьер'
    const JalalAbad_kurer     = 43; //'Джалал-Абад курьер'
    const Uzgen               = 44; //'Узген'
    const Sokulik_pochta      = 45; //'Сокулык Почта'
    const Bazarkorgon_pochta  = 46; //'Базаркоргон Почта'
    const Kant_pochta         = 47; //'Кант Почта'
    const Balkichi_kurer      = 48; //'Балыкчи курьер'
    const Novopokrovka_pochta = 49; //'Новопокровка Почта'
    const Ivanovka_pochta     = 50; //'Ивановка Почта'
    const Nookat_pochta       = 51; //'Ноокат Почта'
    const Novopavlovka_kurer  = 52; //'Новопавловка курьер'
    const Cholpon_pochta      = 53; //'Чолпон Почта'
    const Bostari_pochta      = 54; //'Бостари Почта'
    const Belovodskoe_pochta  = 55; //'Беловодское Почта'
    const Karasu_kurer        = 58; //'Карасу курьер'

    const Kemin_pochta = 66; //'Кемин Почта'

    const Suzak_pochta      = 68; //'Сузак Почта'
    const Massi_pochta      = 69; //'Массы Почта'
    const KochkorAta_pochta = 70; //'Кочкор ата Почта'
    const Aravan_pochta     = 75; //'Араван Почта'
    const Sulukta_pochta    = 79; //'Сулюкта почта'
    const Isfana_kurer      = 80; //'Исфана курьер'
    const Kochkorka_pochta  = 81; //'Кочкорка почта'
    const TashKumir_kurer   = 82; //'Таш-Кумыр курьер'
    const Toktogul_pochta   = 83; //'Токтогул почта'
    const Karakul_pochta    = 84; //'Каракуль почта'
    const MailySuu_pochta   = 85; //'Майлуу-Суу почта'


//---- Армения
    const ARM_pochta   = 61; //'Почта АРМ'
    const Erevan_kurer = 62; //'Ереван курьер'

//---- Россия
    const Novosibirsk     = 107; //'Новосибирск'
    const Omsk            = 108; //'Омск'
    const Berdsk          = 135; //'Бердск'
    const Iskitim         = 136; //'Искитим'
    const Kuibishev       = 137; //'Куйбышев'
    const Linevo          = 138; //'Линево'
    const Kalachinsk      = 139; //'Калачинск'
    const Moskalenki      = 140; //'Москаленки'
    const Tara            = 141; //'Тара'
    const Ekaterinburg    = 148; //'Екатеринбург'
    const KamenskUralskij = 149; //'Каменск-Уральский'
    const Lesnoj          = 150; //'Лесной'
    const Novouralsk      = 151; //'Новоуральск'
    const Serov           = 152; //'Серов'
    const Isilkul         = 153; //'Исилькуль'
}